services:
  mcp-server-chart:
    build:
      context: .          # Dockerfile dir
      dockerfile: Dockerfile
    image: mcp-server-chart:stable
    container_name: mcp-server-chart-1
    environment:
      - MCP_TRANSPORT=sse
      - HOST=0.0.0.0
      - PORT=1122
      # - VIS_REQUEST_SERVER=http://127.0.0.1:3000/render
    ports:
      - "1122:1122"
# networks:
#     - internal
